# 1 numpyのオブジェクト

In [1]:
import numpy as np
np.random.seed(0)

In [2]:
sample_list1 = [1, 2, 3, 4]
sample_list2 = [1, 2, "a", "b"]
sample_ndarray1 = np.array(sample_list1)
sample_ndarray2 = np.array(sample_list2)

print(type(np))

print("\nsample_ndarray1")
print(sample_ndarray1, type(sample_ndarray1), sample_ndarray1.dtype)
print(sample_ndarray1[1], type(sample_ndarray1[1]))
print(sample_ndarray1.astype(float))

print("\nsample_ndarray2")
print(sample_ndarray2, type(sample_ndarray2), sample_ndarray2.dtype)
print(sample_ndarray2[1], type(sample_ndarray2[1]))

<class 'module'>

sample_ndarray1
[1 2 3 4] <class 'numpy.ndarray'> int64
2 <class 'numpy.int64'>
[1. 2. 3. 4.]

sample_ndarray2
['1' '2' 'a' 'b'] <class 'numpy.ndarray'> <U21
2 <class 'numpy.str_'>


# 2 ndarrayの作成

In [3]:
print("他の型からの変換")
print(np.array([1, 2, 3, 4]))
print(np.array((1, 2, 3, 4)))

print("ランダムな配列作成")
print(np.random.rand(2, 3))
print(np.random.randn(2, 3))
print(np.random.randint(0, 10, (3, 4)))
print(np.random.normal(50, 10, (2, 3)))

print("定数の配列作成")
print(np.zeros((2,3)))
print(np.ones((2,3)))

print("順番")
print(np.arange(10))
print(np.arange(3, 8))
print(np.arange(0, 10, 2))

他の型からの変換
[1 2 3 4]
[1 2 3 4]
ランダムな配列作成
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]
[[ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]]
[[8 1 5 9]
 [8 9 4 3]
 [0 3 5 0]]
[[64.94079073 47.94841736 53.13067702]
 [41.45904261 24.47010184 56.53618595]]
定数の配列作成
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
順番
[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]
[0 2 4 6 8]


In [4]:
sample_arr3 = np.random.randint(0, 10, (2, 2, 3))

print(sample_arr3)

print("\n形")
print(sample_arr3.shape, sample_arr3.size, sample_arr3.ndim)

print("\n形の変更")
print(sample_arr3.reshape(4, 3))
print(sample_arr3.transpose(0, 2, 1))
print(sample_arr3.transpose(0, 2, 1).shape)

[[[3 2 7]
  [2 0 0]]

 [[4 5 5]
  [6 8 4]]]

形
(2, 2, 3) 12 3

形の変更
[[3 2 7]
 [2 0 0]
 [4 5 5]
 [6 8 4]]
[[[3 2]
  [2 0]
  [7 0]]

 [[4 6]
  [5 8]
  [5 4]]]
(2, 3, 2)


# 3 参照

In [5]:
sample_arr4 = np.random.randint(0, 10, (2, 3))
print(sample_arr4)

print("\nindex")
print(sample_arr4[0])
print(sample_arr4[0, 2])
print(sample_arr4[0, 1:3])
print(sample_arr4[:, 2])

print("\n条件")
print(sample_arr4[sample_arr4 > 5])

print("\nmask")
print(np.where(sample_arr4 > 5, 1, 0))

[[1 4 9]
 [8 1 1]]

index
[1 4 9]
9
[4 9]
[9 1]

条件
[9 8]

mask
[[0 0 1]
 [1 0 0]]


# 4 演算

In [6]:
arr_A = np.ones((2, 3))
arr_B = np.ones((2, 3)) * 2
arr_C = np.ones((3, 2)) * 3

print("arr_A\n", arr_A)
print("arr_B\n", arr_B)
print("arr_C\n", arr_C)

print("四則演算")
print(arr_A + arr_B)
print(arr_A - arr_B)
print(arr_A * arr_B)
print(arr_A / arr_B)

print("行列の演算")
print(np.dot(arr_A, arr_C))

arr_A
 [[1. 1. 1.]
 [1. 1. 1.]]
arr_B
 [[2. 2. 2.]
 [2. 2. 2.]]
arr_C
 [[3. 3.]
 [3. 3.]
 [3. 3.]]
四則演算
[[3. 3. 3.]
 [3. 3. 3.]]
[[-1. -1. -1.]
 [-1. -1. -1.]]
[[2. 2. 2.]
 [2. 2. 2.]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
行列の演算
[[9. 9.]
 [9. 9.]]


# 5 関数とメソッド

In [7]:
sample_arr5 = np.random.randint(1, 5, (2, 3))

print("sample_arr5")
print(sample_arr5)

print("\n数学の関数")
print(np.abs(sample_arr5))
print(np.sqrt(sample_arr5))
print(np.log(sample_arr5))
print(np.exp(sample_arr5))
print(np.power(sample_arr5, 2))

print("\n統計量に関する関数")
print(np.mean(sample_arr5))
print(np.mean(sample_arr5, axis=0))
print(np.mean(sample_arr5, axis=1))
print(np.std(sample_arr5))
print(np.sum(sample_arr5))
print(np.median(sample_arr5))

print("\n最小値と最大値")
print(np.min(sample_arr5))
print(np.max(sample_arr5))

print("\n最小値と最大値のインデックス")
print(np.argmin(sample_arr5))
print(np.argmax(sample_arr5))

print("\n特殊な関数")
print(np.unique(sample_arr5))
print(np.sort(sample_arr5))

sample_arr5
[[4 2 2]
 [4 3 4]]

数学の関数
[[4 2 2]
 [4 3 4]]
[[2.         1.41421356 1.41421356]
 [2.         1.73205081 2.        ]]
[[1.38629436 0.69314718 0.69314718]
 [1.38629436 1.09861229 1.38629436]]
[[54.59815003  7.3890561   7.3890561 ]
 [54.59815003 20.08553692 54.59815003]]
[[16  4  4]
 [16  9 16]]

統計量に関する関数
3.1666666666666665
[4.  2.5 3. ]
[2.66666667 3.66666667]
0.8975274678557507
19
3.5

最小値と最大値
2
4

最小値と最大値のインデックス
1
0

特殊な関数
[2 3 4]
[[2 2 4]
 [3 4 4]]


In [8]:
print("sample_arr5")
print(sample_arr5)

print("\n統計量に関する関数")
print(sample_arr5.mean())
print(sample_arr5.mean(axis=0))
print(sample_arr5.mean(axis=1))
print(sample_arr5.std())
print(sample_arr5.sum())

print("\n最小値と最大値")
print(sample_arr5.min())
print(sample_arr5.max())

print("\n最小値と最大値のインデックス")
print(sample_arr5.argmin())
print(sample_arr5.argmax())

print("\n特殊な関数")
sample_arr5.sort()
print(sample_arr5)

sample_arr5
[[4 2 2]
 [4 3 4]]

統計量に関する関数
3.1666666666666665
[4.  2.5 3. ]
[2.66666667 3.66666667]
0.8975274678557507
19

最小値と最大値
2
4

最小値と最大値のインデックス
1
0

特殊な関数
[[2 2 4]
 [3 4 4]]
